import type { InvoiceDraft } from '../types/invoice';

export const demoInvoiceDraft: InvoiceDraft = {
  seller: {
    tradeName: 'ABC Manufacturing Pvt Ltd',
    legalName: 'ABC Manufacturing Private Limited',
    addressLine1: '42 Industrial Estate, Phase 2',
    addressLine2: 'Near Metro Pillar 220',
    city: 'Bengaluru',
    stateCode: '29',
    pinCode: '560001',
    phone: '+91 9876543210',
    email: 'accounts@abc.in',
    pan: 'AAECA1234D',
    gstin: '29AAECA1234D1Z5',
    isUnregistered: false,
    jurisdiction: 'Bengaluru Urban',
  },
  buyer: {
    buyerName: 'ABC Traders',
    companyName: 'ABC Retail LLP',
    addressLine1: '17 Market Road',
    addressLine2: 'MG Road',
    city: 'Mysuru',
    stateCode: '29',
    pinCode: '570001',
    phone: '+91 9988776655',
    email: 'billing@abc.in',
    pan: 'AABCR8899K',
    gstin: '29AABCR8899K1Z8',
    placeOfSupplyCode: '29',
    isUnregistered: false,
  },
  invoiceMeta: {
    invoiceNumber: 'ACME/2026/0012',
    invoiceDate: new Date().toISOString().slice(0, 10),
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    reverseCharge: false,
    supplyType: 'mixed',
    currency: 'INR',
    notes: 'Goods once sold will not be taken back.',
    terms: 'Payment due within 7 days.',
    poNumber: 'PO-45889',
    reference: 'Dispatch Ref-2026-45',
  },
  lineItems: [
    {
      id: 'line-1',
      type: 'goods',
      name: 'LED Monitor 24 inch',
      description: 'FHD IPS display',
      hsnSac: '8528',
      unit: 'Nos',
      quantity: 2,
      rate: 8500,
      taxRate: 18,
      discountMode: 'percent',
      discountValue: 5,
    },
    {
      id: 'line-2',
      type: 'service',
      name: 'Installation Service',
      description: 'On-site installation and testing',
      hsnSac: '9987',
      unit: '',
      quantity: 1,
      rate: 1500,
      taxRate: 18,
      discountMode: 'flat',
      discountValue: 0,
    },
  ],
  chargesDiscount: {
    shipping: {
      enabled: true,
      mode: 'flat',
      value: 350,
      taxable: true,
      beforeTax: true,
    },
    packing: {
      enabled: false,
      mode: 'flat',
      value: 0,
      taxable: true,
      beforeTax: true,
    },
    additional: {
      enabled: false,
      mode: 'flat',
      value: 0,
      taxable: false,
      beforeTax: false,
    },
    overallDiscount: {
      enabled: false,
      mode: 'percent',
      value: 0,
      beforeTax: true,
    },
    roundOff: 0,
  },
  paymentDetails: {
    bankAccountName: 'ABC Private Limited',
    bankName: 'State Bank of India',
    accountNumber: '12345678901',
    ifsc: 'SBIN0001234',
    branch: 'MG Road',
    upiId: 'acme@oksbi',
    paymentTerms: 'NEFT/RTGS/UPI accepted',
    showBankDetails: true,
    showUpiQr: true,
  },
  layoutSettings: {
    pageSize: 'A4',
    orientation: 'portrait',
    marginPreset: 'medium',
    customMarginMm: 12,
    autoFit: true,
    fontScale: 1,
    compactMode: false,
    showSellerLogo: true,
    showBuyerGSTIN: true,
    showBuyerPAN: true,
    showHSN: true,
    showTaxRate: true,
    showLineDiscount: true,
    showBankDetails: true,
    showUpiQr: true,
    showNotes: true,
    showJurisdiction: true,
    showSignatureBlock: true,
    showTaxSummary: true,
    showHsnSummary: true,
    showPageNumbers: true,
    showAuthorizedSignatory: true,
    showAmountInWords: true,
    footerText: 'This is a computer-generated invoice.',
    signatureAlignment: 'right',
    invoiceTheme: 'classic',
    storageMode: 'session',
    darkMode: false,
  },
};
